# Generated by Django 4.2.5 on 2023-10-31 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_customuser_delete_choice_delete_question"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
