# Generated by Django 4.2.5 on 2023-10-31 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
